test: $(OBJS)
	@if [ -d tests ]; then cd tests && make --no-print-directory; fi

clean:
	@find \( -regex '.*\.\([oa]\|gch\)' -or -name 'test-exec' \) -exec rm -f {} \;
	@rm -f $(EXE) $(OBJS) $(OUT) $(OUTLIB)
	@if [ -d tests ]; then cd tests && make --no-print-directory clean; fi

%.o: %.cpp
	@echo CC $<
	${CXX} -c ${CXXFLAGS} $<

$(OUTLIB): $(OBJS)
	@echo Linking $($?) to $(OUTLIB)
	$(AR) rs $(OUTLIB) $? >/dev/null

# vim: set filetype=make : #
