include ../Makefile.inc

OBJS = Buffer.o Reader.o
OUTLIB = ../libbuffer.a

all: $(OBJS) test $(OUTLIB)

Buffer.o: Buffer.hpp Constants.hpp
Reader.o: Reader.hpp Constants.hpp

include ../Makefile.stdrules
