include ../Makefile.inc

OUTLIB = ../libpars.a

all: $(OBJS) test $(OUTLIB)

Parser.o: Parser.cpp Parser.hpp Rule.hpp
ParseTree.o: ParseTree.cpp ParseTree.hpp
Node.o: Node.cpp Node.hpp

include ../Makefile.stdrules
