#!/usr/bin/perl -w

$name = "TType";
@names = ("no_type", "integer", "identifier", "print", "read", "if", "else", "while", "int");
@signnames = (
    "addititon",
    "subtraction",
    "division",
    "multiplication",
    "lt",
    "gt",
    "assign",
    "ne",
    "exclamation",
    "ampersand",
    "semicolon",
    "colon",
    "leftBracket",
    "rightBracket",
    "leftAngleBracket",
    "rightAngleBracket",
    "leftSquareBracket",
    "rightSquareBracket"
);

&makeit;






$name = "Status";
@names = (
    "NONE",

    "FINAL",
    "FINAL_COMMENT_NOT_CLOSED_ERROR",
    "ERROR",

    "READING_COMMENT",
    "READING_IDENTIFIER",
    "READING_INT",
    "READING_SIGN",

    "READ_IDENTIFIER",
    "READ_INT",
    "READ_SIGN",

    "NEWLINE"
);
undef(@signnames);

&makeit;


print ">>>>>>>>>>> Remember to change the _str-strings wherevere used to avoid confusion! <<<<<<<<<<<<\n";






sub makeit {
    $def = "\U$name";
    $low = "\L$name";

    open HFILE, ">$name.hpp";
    #open CFILE, ">$name.cpp";
    print HFILE "#ifndef $def\n#define $def\n\nenum $name { ";

    print HFILE join(", ", split(" ", "\U@names"));
    if ($#signnames > 0) {
        print HFILE ", ";
        print HFILE join(", SIGN_", split(" ", "\USIGN_@signnames"));
    }
    print HFILE " };\n\n";

    print HFILE '//const char* '.$low.'_str[] = { "';
    print HFILE join('", "', split(" ", "\U@names @signnames"));
    print HFILE '" };';

    print HFILE "\n\n#endif";
    print HFILE "\n";
}
