#ifndef STATUS
#define STATUS

enum Status { NONE, FINAL, ERROR, READING_COMMENT, READING_IDENTIFIER, READING_INT, READING_SIGN, READ_IDENTIFIER, READ_INT, READ_SIGN, TOKEN_READ, NEWLINE };

//const char* status_str[] = { "NONE", "FINAL", "ERROR", "READING_COMMENT", "READING_IDENTIFIER", "READING_INT", "READING_SIGN", "READ_IDENTIFIER", "READ_INT", "READ_SIGN", "TOKEN_READ", "NEWLINE" };

#endif
