#ifndef TTYPE_H
#define TTYPE_H

enum TType { NO_TYPE, INTEGER, IDENTIFIER, PRINT, READ, IF, ELSE, WHILE, INT, SIGN_ADDITITON, SIGN_SUBTRACTION, SIGN_DIVISION, SIGN_MULTIPLICATION, SIGN_LT, SIGN_GT, SIGN_ASSIGN, SIGN_NE, SIGN_EXCLAMATION, SIGN_AMPERSAND, SIGN_SEMICOLON, SIGN_COLON, SIGN_LEFTBRACKET, SIGN_RIGHTBRACKET, SIGN_LEFTANGLEBRACKET, SIGN_RIGHTANGLEBRACKET, SIGN_LEFTSQUAREBRACKET, SIGN_RIGHTSQUAREBRACKET };

#endif
