include ../Makefile.inc

OUTLIB = ../libsymtab.a

all: $(OBJS) test $(OUTLIB)

Symtable.o: Symtable.hpp Constants.hpp
StringTab.o: StringTab.hpp Constants.hpp
StringTabNode.o: StringTabNode.hpp Constants.hpp

include ../Makefile.stdrules
