#ifndef STATUS
#define STATUS

enum Status { FINAL, ERROR, NONE, READING_INT, READING_IDENTIFIER, READING_SIGN, READ_INT, READ_IDENTIFIER, READ_SIGN, TOKEN_READ, NEWLINE };

//const char* status_str[] = { "FINAL", "ERROR", "NONE", "READING_INT", "READING_IDENTIFIER", "READING_SIGN", "READ_INT", "READ_IDENTIFIER", "READ_SIGN", "TOKEN_READ", "NEWLINE" };

#endif
