#ifndef TTYPE
#define TTYPE

enum TType { INTEGER, IDENTIFIER, PRINT, READ, SIGN_ADDITITON, SIGN_SUBTRACTION, SIGN_DIVISION, SIGN_MULTIPLICATION, SIGN_LT, SIGN_GT, SIGN_ASSIGN, SIGN_NE, SIGN_EXCLAMATION, SIGN_AMPERSAND, SIGN_SEMICOLON, SIGN_LEFTBRACKET, SIGN_RIGHTBRACKET, SIGN_LEFTANGLEBRACKET, SIGN_RIGHTANGLEBRACKET, SIGN_LEFTSQUAREBRACKET, SIGN_RIGHTSQUAREBRACKET };

//const char* ttype_str[] = { "INTEGER", "IDENTIFIER", "PRINT", "READ", "ADDITITON", "SUBTRACTION", "DIVISION", "MULTIPLICATION", "LT", "GT", "ASSIGN", "NE", "EXCLAMATION", "AMPERSAND", "SEMICOLON", "LEFTBRACKET", "RIGHTBRACKET", "LEFTANGLEBRACKET", "RIGHTANGLEBRACKET", "LEFTSQUAREBRACKET", "RIGHTSQUAREBRACKET" };

#endif
